# Generated by Django 4.1.7 on 2023-04-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='empolye',
            new_name='employe',
        ),
    ]
